# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from project_api.models.base_model_ import Model
from project_api import util


class BluestV3PayloadDecodingSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, telemetry: str=None, type: str=None):  # noqa: E501
        """BluestV3PayloadDecodingSchema - a model defined in Swagger

        :param telemetry: The telemetry of this BluestV3PayloadDecodingSchema.  # noqa: E501
        :type telemetry: str
        :param type: The type of this BluestV3PayloadDecodingSchema.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'telemetry': str,
            'type': str
        }

        self.attribute_map = {
            'telemetry': 'telemetry',
            'type': 'type'
        }
        self._telemetry = telemetry
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'BluestV3PayloadDecodingSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BluestV3Payload_decoding_schema of this BluestV3PayloadDecodingSchema.  # noqa: E501
        :rtype: BluestV3PayloadDecodingSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def telemetry(self) -> str:
        """Gets the telemetry of this BluestV3PayloadDecodingSchema.


        :return: The telemetry of this BluestV3PayloadDecodingSchema.
        :rtype: str
        """
        return self._telemetry

    @telemetry.setter
    def telemetry(self, telemetry: str):
        """Sets the telemetry of this BluestV3PayloadDecodingSchema.


        :param telemetry: The telemetry of this BluestV3PayloadDecodingSchema.
        :type telemetry: str
        """

        self._telemetry = telemetry

    @property
    def type(self) -> str:
        """Gets the type of this BluestV3PayloadDecodingSchema.


        :return: The type of this BluestV3PayloadDecodingSchema.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this BluestV3PayloadDecodingSchema.


        :param type: The type of this BluestV3PayloadDecodingSchema.
        :type type: str
        """

        self._type = type
