# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bluest_v3_payload_decoding_schema import BluestV3PayloadDecodingSchema  # noqa: F401,E501
from swagger_server import util


class BluestV3Payload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, device_id: str=None, fw_id: str=None, payload_id: str=None, decoding_schema: List[BluestV3PayloadDecodingSchema]=None):  # noqa: E501
        """BluestV3Payload - a model defined in Swagger

        :param device_id: The device_id of this BluestV3Payload.  # noqa: E501
        :type device_id: str
        :param fw_id: The fw_id of this BluestV3Payload.  # noqa: E501
        :type fw_id: str
        :param payload_id: The payload_id of this BluestV3Payload.  # noqa: E501
        :type payload_id: str
        :param decoding_schema: The decoding_schema of this BluestV3Payload.  # noqa: E501
        :type decoding_schema: List[BluestV3PayloadDecodingSchema]
        """
        self.swagger_types = {
            'device_id': str,
            'fw_id': str,
            'payload_id': str,
            'decoding_schema': List[BluestV3PayloadDecodingSchema]
        }

        self.attribute_map = {
            'device_id': 'device_id',
            'fw_id': 'fw_id',
            'payload_id': 'payload_id',
            'decoding_schema': 'decoding_schema'
        }
        self._device_id = device_id
        self._fw_id = fw_id
        self._payload_id = payload_id
        self._decoding_schema = decoding_schema

    @classmethod
    def from_dict(cls, dikt) -> 'BluestV3Payload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BluestV3Payload of this BluestV3Payload.  # noqa: E501
        :rtype: BluestV3Payload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_id(self) -> str:
        """Gets the device_id of this BluestV3Payload.


        :return: The device_id of this BluestV3Payload.
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id: str):
        """Sets the device_id of this BluestV3Payload.


        :param device_id: The device_id of this BluestV3Payload.
        :type device_id: str
        """

        self._device_id = device_id

    @property
    def fw_id(self) -> str:
        """Gets the fw_id of this BluestV3Payload.


        :return: The fw_id of this BluestV3Payload.
        :rtype: str
        """
        return self._fw_id

    @fw_id.setter
    def fw_id(self, fw_id: str):
        """Sets the fw_id of this BluestV3Payload.


        :param fw_id: The fw_id of this BluestV3Payload.
        :type fw_id: str
        """

        self._fw_id = fw_id

    @property
    def payload_id(self) -> str:
        """Gets the payload_id of this BluestV3Payload.


        :return: The payload_id of this BluestV3Payload.
        :rtype: str
        """
        return self._payload_id

    @payload_id.setter
    def payload_id(self, payload_id: str):
        """Sets the payload_id of this BluestV3Payload.


        :param payload_id: The payload_id of this BluestV3Payload.
        :type payload_id: str
        """

        self._payload_id = payload_id

    @property
    def decoding_schema(self) -> List[BluestV3PayloadDecodingSchema]:
        """Gets the decoding_schema of this BluestV3Payload.


        :return: The decoding_schema of this BluestV3Payload.
        :rtype: List[BluestV3PayloadDecodingSchema]
        """
        return self._decoding_schema

    @decoding_schema.setter
    def decoding_schema(self, decoding_schema: List[BluestV3PayloadDecodingSchema]):
        """Sets the decoding_schema of this BluestV3Payload.


        :param decoding_schema: The decoding_schema of this BluestV3Payload.
        :type decoding_schema: List[BluestV3PayloadDecodingSchema]
        """

        self._decoding_schema = decoding_schema
