# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EFSUsage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, efs_usage_breached: bool=None):  # noqa: E501
        """EFSUsage - a model defined in Swagger

        :param efs_usage_breached: The efs_usage_breached of this EFSUsage.  # noqa: E501
        :type efs_usage_breached: bool
        """
        self.swagger_types = {
            'efs_usage_breached': bool
        }

        self.attribute_map = {
            'efs_usage_breached': 'efs_usage_breached'
        }
        self._efs_usage_breached = efs_usage_breached

    @classmethod
    def from_dict(cls, dikt) -> 'EFSUsage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EFSUsage of this EFSUsage.  # noqa: E501
        :rtype: EFSUsage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def efs_usage_breached(self) -> bool:
        """Gets the efs_usage_breached of this EFSUsage.


        :return: The efs_usage_breached of this EFSUsage.
        :rtype: bool
        """
        return self._efs_usage_breached

    @efs_usage_breached.setter
    def efs_usage_breached(self, efs_usage_breached: bool):
        """Sets the efs_usage_breached of this EFSUsage.


        :param efs_usage_breached: The efs_usage_breached of this EFSUsage.
        :type efs_usage_breached: bool
        """

        self._efs_usage_breached = efs_usage_breached
