# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.dataset import Dataset  # noqa: F401,E501
from swagger_server.models.model_type import ModelType  # noqa: F401,E501
from swagger_server.models.target import Target  # noqa: F401,E501
from swagger_server.models.training_type import TrainingType  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class NewModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, model_name_to_clone: str=None, name: str=None, model_type: ModelType=None, dataset: Dataset=None, classes: List[str]=None, training_type: TrainingType=None, target: Target=None, creation_time: str=None, last_update_time: str=None, model_owner_uuid: str=None):  # noqa: E501
        """NewModel - a model defined in Swagger

        :param model_name_to_clone: The model_name_to_clone of this NewModel.  # noqa: E501
        :type model_name_to_clone: str
        :param name: The name of this NewModel.  # noqa: E501
        :type name: str
        :param model_type: The model_type of this NewModel.  # noqa: E501
        :type model_type: ModelType
        :param dataset: The dataset of this NewModel.  # noqa: E501
        :type dataset: Dataset
        :param classes: The classes of this NewModel.  # noqa: E501
        :type classes: List[str]
        :param training_type: The training_type of this NewModel.  # noqa: E501
        :type training_type: TrainingType
        :param target: The target of this NewModel.  # noqa: E501
        :type target: Target
        :param creation_time: The creation_time of this NewModel.  # noqa: E501
        :type creation_time: str
        :param last_update_time: The last_update_time of this NewModel.  # noqa: E501
        :type last_update_time: str
        :param model_owner_uuid: The model_owner_uuid of this NewModel.  # noqa: E501
        :type model_owner_uuid: str
        """
        self.swagger_types = {
            'model_name_to_clone': str,
            'name': str,
            'model_type': ModelType,
            'dataset': Dataset,
            'classes': List[str],
            'training_type': TrainingType,
            'target': Target,
            'creation_time': str,
            'last_update_time': str,
            'model_owner_uuid': str
        }

        self.attribute_map = {
            'model_name_to_clone': 'model_name_to_clone',
            'name': 'name',
            'model_type': 'model_type',
            'dataset': 'dataset',
            'classes': 'classes',
            'training_type': 'training_type',
            'target': 'target',
            'creation_time': 'creation_time',
            'last_update_time': 'last_update_time',
            'model_owner_uuid': 'model_owner_uuid'
        }
        self._model_name_to_clone = model_name_to_clone
        self._name = name
        self._model_type = model_type
        self._dataset = dataset
        self._classes = classes
        self._training_type = training_type
        self._target = target
        self._creation_time = creation_time
        self._last_update_time = last_update_time
        self._model_owner_uuid = model_owner_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'NewModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewModel of this NewModel.  # noqa: E501
        :rtype: NewModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_name_to_clone(self) -> str:
        """Gets the model_name_to_clone of this NewModel.


        :return: The model_name_to_clone of this NewModel.
        :rtype: str
        """
        return self._model_name_to_clone

    @model_name_to_clone.setter
    def model_name_to_clone(self, model_name_to_clone: str):
        """Sets the model_name_to_clone of this NewModel.


        :param model_name_to_clone: The model_name_to_clone of this NewModel.
        :type model_name_to_clone: str
        """

        self._model_name_to_clone = model_name_to_clone

    @property
    def name(self) -> str:
        """Gets the name of this NewModel.


        :return: The name of this NewModel.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this NewModel.


        :param name: The name of this NewModel.
        :type name: str
        """

        self._name = name

    @property
    def model_type(self) -> ModelType:
        """Gets the model_type of this NewModel.


        :return: The model_type of this NewModel.
        :rtype: ModelType
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type: ModelType):
        """Sets the model_type of this NewModel.


        :param model_type: The model_type of this NewModel.
        :type model_type: ModelType
        """

        self._model_type = model_type

    @property
    def dataset(self) -> Dataset:
        """Gets the dataset of this NewModel.


        :return: The dataset of this NewModel.
        :rtype: Dataset
        """
        return self._dataset

    @dataset.setter
    def dataset(self, dataset: Dataset):
        """Sets the dataset of this NewModel.


        :param dataset: The dataset of this NewModel.
        :type dataset: Dataset
        """

        self._dataset = dataset

    @property
    def classes(self) -> List[str]:
        """Gets the classes of this NewModel.


        :return: The classes of this NewModel.
        :rtype: List[str]
        """
        return self._classes

    @classes.setter
    def classes(self, classes: List[str]):
        """Sets the classes of this NewModel.


        :param classes: The classes of this NewModel.
        :type classes: List[str]
        """

        self._classes = classes

    @property
    def training_type(self) -> TrainingType:
        """Gets the training_type of this NewModel.


        :return: The training_type of this NewModel.
        :rtype: TrainingType
        """
        return self._training_type

    @training_type.setter
    def training_type(self, training_type: TrainingType):
        """Sets the training_type of this NewModel.


        :param training_type: The training_type of this NewModel.
        :type training_type: TrainingType
        """

        self._training_type = training_type

    @property
    def target(self) -> Target:
        """Gets the target of this NewModel.


        :return: The target of this NewModel.
        :rtype: Target
        """
        return self._target

    @target.setter
    def target(self, target: Target):
        """Sets the target of this NewModel.


        :param target: The target of this NewModel.
        :type target: Target
        """

        self._target = target

    @property
    def creation_time(self) -> str:
        """Gets the creation_time of this NewModel.


        :return: The creation_time of this NewModel.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time: str):
        """Sets the creation_time of this NewModel.


        :param creation_time: The creation_time of this NewModel.
        :type creation_time: str
        """

        self._creation_time = creation_time

    @property
    def last_update_time(self) -> str:
        """Gets the last_update_time of this NewModel.


        :return: The last_update_time of this NewModel.
        :rtype: str
        """
        return self._last_update_time

    @last_update_time.setter
    def last_update_time(self, last_update_time: str):
        """Sets the last_update_time of this NewModel.


        :param last_update_time: The last_update_time of this NewModel.
        :type last_update_time: str
        """

        self._last_update_time = last_update_time

    @property
    def model_owner_uuid(self) -> str:
        """Gets the model_owner_uuid of this NewModel.


        :return: The model_owner_uuid of this NewModel.
        :rtype: str
        """
        return self._model_owner_uuid

    @model_owner_uuid.setter
    def model_owner_uuid(self, model_owner_uuid: str):
        """Sets the model_owner_uuid of this NewModel.


        :param model_owner_uuid: The model_owner_uuid of this NewModel.
        :type model_owner_uuid: str
        """

        self._model_owner_uuid = model_owner_uuid
