# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsprojectNamedeploymentsDeploymentInferenceModels(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, artifact_type: str=None, component_name: str=None, model_name_reference: str=None):  # noqa: E501
        """ProjectsprojectNamedeploymentsDeploymentInferenceModels - a model defined in Swagger

        :param artifact_type: The artifact_type of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.  # noqa: E501
        :type artifact_type: str
        :param component_name: The component_name of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.  # noqa: E501
        :type component_name: str
        :param model_name_reference: The model_name_reference of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.  # noqa: E501
        :type model_name_reference: str
        """
        self.swagger_types = {
            'artifact_type': str,
            'component_name': str,
            'model_name_reference': str
        }

        self.attribute_map = {
            'artifact_type': 'artifact_type',
            'component_name': 'component_name',
            'model_name_reference': 'model_name_reference'
        }
        self._artifact_type = artifact_type
        self._component_name = component_name
        self._model_name_reference = model_name_reference

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsprojectNamedeploymentsDeploymentInferenceModels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projectsproject_namedeployments_deployment_inference_models of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.  # noqa: E501
        :rtype: ProjectsprojectNamedeploymentsDeploymentInferenceModels
        """
        return util.deserialize_model(dikt, cls)

    @property
    def artifact_type(self) -> str:
        """Gets the artifact_type of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.


        :return: The artifact_type of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.
        :rtype: str
        """
        return self._artifact_type

    @artifact_type.setter
    def artifact_type(self, artifact_type: str):
        """Sets the artifact_type of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.


        :param artifact_type: The artifact_type of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.
        :type artifact_type: str
        """

        self._artifact_type = artifact_type

    @property
    def component_name(self) -> str:
        """Gets the component_name of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.


        :return: The component_name of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.
        :rtype: str
        """
        return self._component_name

    @component_name.setter
    def component_name(self, component_name: str):
        """Sets the component_name of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.


        :param component_name: The component_name of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.
        :type component_name: str
        """

        self._component_name = component_name

    @property
    def model_name_reference(self) -> str:
        """Gets the model_name_reference of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.


        :return: The model_name_reference of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.
        :rtype: str
        """
        return self._model_name_reference

    @model_name_reference.setter
    def model_name_reference(self, model_name_reference: str):
        """Sets the model_name_reference of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.


        :param model_name_reference: The model_name_reference of this ProjectsprojectNamedeploymentsDeploymentInferenceModels.
        :type model_name_reference: str
        """

        self._model_name_reference = model_name_reference
