# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsprojectNamedeploymentsDeploymentDatalogging(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, application: str=None, firmware_update: bool=None):  # noqa: E501
        """ProjectsprojectNamedeploymentsDeploymentDatalogging - a model defined in Swagger

        :param application: The application of this ProjectsprojectNamedeploymentsDeploymentDatalogging.  # noqa: E501
        :type application: str
        :param firmware_update: The firmware_update of this ProjectsprojectNamedeploymentsDeploymentDatalogging.  # noqa: E501
        :type firmware_update: bool
        """
        self.swagger_types = {
            'application': str,
            'firmware_update': bool
        }

        self.attribute_map = {
            'application': 'application',
            'firmware_update': 'firmware_update'
        }
        self._application = application
        self._firmware_update = firmware_update

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsprojectNamedeploymentsDeploymentDatalogging':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projectsproject_namedeployments_deployment_datalogging of this ProjectsprojectNamedeploymentsDeploymentDatalogging.  # noqa: E501
        :rtype: ProjectsprojectNamedeploymentsDeploymentDatalogging
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application(self) -> str:
        """Gets the application of this ProjectsprojectNamedeploymentsDeploymentDatalogging.


        :return: The application of this ProjectsprojectNamedeploymentsDeploymentDatalogging.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application: str):
        """Sets the application of this ProjectsprojectNamedeploymentsDeploymentDatalogging.


        :param application: The application of this ProjectsprojectNamedeploymentsDeploymentDatalogging.
        :type application: str
        """

        self._application = application

    @property
    def firmware_update(self) -> bool:
        """Gets the firmware_update of this ProjectsprojectNamedeploymentsDeploymentDatalogging.


        :return: The firmware_update of this ProjectsprojectNamedeploymentsDeploymentDatalogging.
        :rtype: bool
        """
        return self._firmware_update

    @firmware_update.setter
    def firmware_update(self, firmware_update: bool):
        """Sets the firmware_update of this ProjectsprojectNamedeploymentsDeploymentDatalogging.


        :param firmware_update: The firmware_update of this ProjectsprojectNamedeploymentsDeploymentDatalogging.
        :type firmware_update: bool
        """

        self._firmware_update = firmware_update
