# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsprojectNamedeploymentsdeploymentIdGateway(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, device_id: str=None, device_id: str=None, application: str=None, description: str=None, display_name: str=None, wifi_mode: str=None):  # noqa: E501
        """ProjectsprojectNamedeploymentsdeploymentIdGateway - a model defined in Swagger

        :param device_id: The device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.  # noqa: E501
        :type device_id: str
        :param device_id: The device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.  # noqa: E501
        :type device_id: str
        :param application: The application of this ProjectsprojectNamedeploymentsdeploymentIdGateway.  # noqa: E501
        :type application: str
        :param description: The description of this ProjectsprojectNamedeploymentsdeploymentIdGateway.  # noqa: E501
        :type description: str
        :param display_name: The display_name of this ProjectsprojectNamedeploymentsdeploymentIdGateway.  # noqa: E501
        :type display_name: str
        :param wifi_mode: The wifi_mode of this ProjectsprojectNamedeploymentsdeploymentIdGateway.  # noqa: E501
        :type wifi_mode: str
        """
        self.swagger_types = {
            'device_id': str,
            'device_id': str,
            'application': str,
            'description': str,
            'display_name': str,
            'wifi_mode': str
        }

        self.attribute_map = {
            'device_id': '_device_id',
            'device_id': 'device_id',
            'application': 'application',
            'description': 'description',
            'display_name': 'display_name',
            'wifi_mode': 'wifi_mode'
        }
        self._device_id = device_id
        self._device_id = device_id
        self._application = application
        self._description = description
        self._display_name = display_name
        self._wifi_mode = wifi_mode

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsprojectNamedeploymentsdeploymentIdGateway':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projectsproject_namedeploymentsdeployment_id_gateway of this ProjectsprojectNamedeploymentsdeploymentIdGateway.  # noqa: E501
        :rtype: ProjectsprojectNamedeploymentsdeploymentIdGateway
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_id(self) -> str:
        """Gets the device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :return: The device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id: str):
        """Sets the device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :param device_id: The device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :type device_id: str
        """

        self._device_id = device_id

    @property
    def device_id(self) -> str:
        """Gets the device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :return: The device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id: str):
        """Sets the device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :param device_id: The device_id of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :type device_id: str
        """

        self._device_id = device_id

    @property
    def application(self) -> str:
        """Gets the application of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :return: The application of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application: str):
        """Sets the application of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :param application: The application of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :type application: str
        """

        self._application = application

    @property
    def description(self) -> str:
        """Gets the description of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :return: The description of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :param description: The description of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :type description: str
        """

        self._description = description

    @property
    def display_name(self) -> str:
        """Gets the display_name of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :return: The display_name of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :param display_name: The display_name of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def wifi_mode(self) -> str:
        """Gets the wifi_mode of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :return: The wifi_mode of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :rtype: str
        """
        return self._wifi_mode

    @wifi_mode.setter
    def wifi_mode(self, wifi_mode: str):
        """Sets the wifi_mode of this ProjectsprojectNamedeploymentsdeploymentIdGateway.


        :param wifi_mode: The wifi_mode of this ProjectsprojectNamedeploymentsdeploymentIdGateway.
        :type wifi_mode: str
        """

        self._wifi_mode = wifi_mode
