# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.update_device_cloud_credentials import UpdateDeviceCloudCredentials  # noqa: F401,E501
from swagger_server import util


class UpdateDevice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cloud_credentials: UpdateDeviceCloudCredentials=None):  # noqa: E501
        """UpdateDevice - a model defined in Swagger

        :param cloud_credentials: The cloud_credentials of this UpdateDevice.  # noqa: E501
        :type cloud_credentials: UpdateDeviceCloudCredentials
        """
        self.swagger_types = {
            'cloud_credentials': UpdateDeviceCloudCredentials
        }

        self.attribute_map = {
            'cloud_credentials': 'cloud_credentials'
        }
        self._cloud_credentials = cloud_credentials

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateDevice of this UpdateDevice.  # noqa: E501
        :rtype: UpdateDevice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cloud_credentials(self) -> UpdateDeviceCloudCredentials:
        """Gets the cloud_credentials of this UpdateDevice.


        :return: The cloud_credentials of this UpdateDevice.
        :rtype: UpdateDeviceCloudCredentials
        """
        return self._cloud_credentials

    @cloud_credentials.setter
    def cloud_credentials(self, cloud_credentials: UpdateDeviceCloudCredentials):
        """Sets the cloud_credentials of this UpdateDevice.


        :param cloud_credentials: The cloud_credentials of this UpdateDevice.
        :type cloud_credentials: UpdateDeviceCloudCredentials
        """

        self._cloud_credentials = cloud_credentials
