# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from project_api.models.base_model_ import Model
from project_api.models.device_application import DeviceApplication  # noqa: F401,E501
from project_api import util


class Device(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, device_id: str=None, description: str=None, display_name: str=None, gateway_id: str=None, wifi_mode: str=None, application: str=None, datalogging: DeviceApplication=None, inference: DeviceApplication=None):  # noqa: E501
        """Device - a model defined in Swagger

        :param device_id: The device_id of this Device.  # noqa: E501
        :type device_id: str
        :param description: The description of this Device.  # noqa: E501
        :type description: str
        :param display_name: The display name of this Device.  # noqa: E501
        :type display_name: str
        :param gateway_id: The gateway_id of this Device.  # noqa: E501
        :type gateway_id: str        
        :param wifi_mode: The wifi_mode of this Device.  # noqa: E501
        :type wifi_mode: str
        :param application: The application identifier of this Device.  # noqa: E501
        :type application: str
        :param datalogging: The datalogging configuration of this Device.  # noqa: E501
        :type datalogging: DeviceApplication
        :param inference: The inference configuration of this Device.  # noqa: E501
        :type inference: DeviceApplication
        """
        self.swagger_types = {
            'device_id': str,
            'description': str,
            'display_name': str,
            'gateway_id': str,
            'wifi_mode': str,
            'application': str,
            'datalogging': DeviceApplication,
            'inference': DeviceApplication
        }

        self.attribute_map = {
            'device_id': 'device_id',
            'description': 'description',
            'display_name': 'display_name',
            'gateway_id': 'gateway_id',
            'wifi_mode': 'wifi_mode',
            'application': 'application',
            'datalogging': 'datalogging',
            'inference': 'inference'
        }
        self._device_id = device_id
        self._description = description
        self._display_name = display_name
        self._gateway_id = gateway_id
        self._wifi_mode = wifi_mode
        self._application = application
        self._datalogging = datalogging
        self._inference = inference

    @classmethod
    def from_dict(cls, dikt) -> 'Device':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Device of this Device.  # noqa: E501
        :rtype: Device
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_id(self) -> str:
        """Gets the device_id of this Device.


        :return: The device_id of this Device.
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id: str):
        """Sets the device_id of this Device.


        :param device_id: The device_id of this Device.
        :type device_id: str
        """
        if device_id is None:
            raise ValueError("Invalid value for `device_id`, must not be `None`")  # noqa: E501

        self._device_id = device_id

    @property
    def description(self) -> str:
        """Gets the description of this Device.


        :return: The description of this Device.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Device.


        :param description: The description of this Device.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def display_name(self) -> str:
        """Gets the display_name of this Device.


        :return: The display_name of this Device.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this Device.


        :param display_name: The display_name of this Device.
        :type display_name: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def gateway_id(self) -> str:
        """Gets the gateway_id of this Device.


        :return: The gateway_id of this Device.
        :rtype: str
        """
        return self._gateway_id

    @gateway_id.setter
    def gateway_id(self, gateway_id: str):
        """Sets the gateway_id of this Device.


        :param gateway_id: The gateway_id of this Device.
        :type gateway_id: str
        """

        self._gateway_id = gateway_id

    @property
    def wifi_mode(self) -> str:
        """Gets the wifi_mode of this Device.


        :return: The wifi_mode of this Device.
        :rtype: str
        """
        return self._wifi_mode

    @wifi_mode.setter
    def wifi_mode(self, wifi_mode: str):
        """Sets the wifi_mode of this Device.


        :param wifi_mode: The wifi_mode of this Device.
        :type wifi_mode: str
        """

        self._wifi_mode = wifi_mode

    @property
    def application(self) -> str:
        """Gets the application identifier of this Device.


        :return: The application of this Device.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application: str):
        """Sets the application of this Device.


        :param application: The application of this Device.
        :type application: str
        """

        self._application = application

    @property
    def datalogging(self) -> DeviceApplication:
        """Gets the datalogging of this Device.


        :return: The datalogging of this Device.
        :rtype: DeviceApplication
        """
        return self._datalogging

    @datalogging.setter
    def datalogging(self, datalogging: DeviceApplication):
        """Sets the datalogging of this Device.


        :param datalogging: The datalogging of this Device.
        :type datalogging: DeviceApplication
        """

        self._datalogging = datalogging

    @property
    def inference(self) -> DeviceApplication:
        """Gets the inference of this Device.


        :return: The inference of this Device.
        :rtype: DeviceApplication
        """
        return self._inference

    @inference.setter
    def inference(self, inference: DeviceApplication):
        """Sets the inference of this Device.


        :param inference: The inference of this Device.
        :type inference: DeviceApplication
        """

        self._inference = inference