# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from project_api import util
from project_api.models.base_model_ import Model
from project_api.models.model_type import ModelType  # noqa: F401,E501


class ModelModelMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, classes: List[str]=None, type: ModelType=None):  # noqa: E501
        """ModelModelMetadata - a model defined in Swagger

        :param classes: The classes of this ModelModelMetadata.  # noqa: E501
        :type classes: List[str]
        """
        self.swagger_types = {
            'classes': List[str],
            'type': ModelType
        }

        self.attribute_map = {
            'classes': 'classes',
            'type': 'type'
        }
        self._classes = classes
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ModelModelMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Model_model_metadata of this ModelModelMetadata.  # noqa: E501
        :rtype: ModelModelMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def classes(self) -> List[str]:
        """Gets the classes of this ModelModelMetadata.


        :return: The classes of this ModelModelMetadata.
        :rtype: List[str]
        """
        return self._classes

    @classes.setter
    def classes(self, classes: List[str]):
        """Sets the classes of this ModelModelMetadata.


        :param classes: The classes of this ModelModelMetadata.
        :type classes: List[str]
        """

        self._classes = classes
    
    @property
    def type(self) -> ModelType:
        """Gets the model_type of this Model.


        :return: The model_type of this Model.
        :rtype: ModelType
        """
        return self._type

    @type.setter
    def type(self, model_type: ModelType):
        """Sets the model_type of this Model.


        :param model_type: The model_type of this Model.
        :type model_type: ModelType
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501

        self._type = model_type
