# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from project_api.models.base_model_ import Model
from project_api.models.deployment_cloud_params import DeploymentCloudParams  # noqa: F401,E501
from project_api.models.device import Device  # noqa: F401,E501
from project_api import util


class NewDeployment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, display_name: str=None, description: str=None, cloud_params: DeploymentCloudParams=None, leaf: List[Device]=None, gateway: List[Device]=None):  # noqa: E501
        """Deployment - a model defined in Swagger

        :param display_name: The display_name of this Deployment.  # noqa: E501
        :type display_name: str
        :param description: The description of this Deployment.  # noqa: E501
        :type description: str
        :param cloud_params: The cloud_params of this Deployment.  # noqa: E501
        :type cloud_params: DeploymentCloudParams
        :param configuration: The configuration of this Deployment.  # noqa: E501
        :type configuration: DeploymentConfiguration
        """
        self.swagger_types = {
            'display_name': str,
            'description': str,
            'cloud_params': DeploymentCloudParams,
            'leaf': List[Device],
            'gateway': List[Device],
        }

        self.attribute_map = {
            'display_name': 'display_name',
            'description': 'description',
            'cloud_params': 'cloud_params',
            'leaf': 'leaf',
            'gateway': 'gateway'
        }
        self._display_name = display_name
        self._description = description
        self._cloud_params = cloud_params
        self._leaf = leaf
        self._gateway = gateway

    @classmethod
    def from_dict(cls, dikt) -> 'NewDeployment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Deployment of this Deployment.  # noqa: E501
        :rtype: Deployment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def display_name(self) -> str:
        """Gets the display_name of this Deployment.


        :return: The display_name of this Deployment.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this Deployment.


        :param display_name: The display_name of this Deployment.
        :type display_name: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self) -> str:
        """Gets the description of this Deployment.


        :return: The description of this Deployment.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Deployment.


        :param description: The description of this Deployment.
        :type description: str
        """

        self._description = description

    @property
    def cloud_params(self) -> DeploymentCloudParams:
        """Gets the cloud_params of this Deployment.


        :return: The cloud_params of this Deployment.
        :rtype: DeploymentCloudParams
        """
        return self._cloud_params

    @cloud_params.setter
    def cloud_params(self, cloud_params: DeploymentCloudParams):
        """Sets the cloud_params of this Deployment.


        :param cloud_params: The cloud_params of this Deployment.
        :type cloud_params: DeploymentCloudParams
        """
        if cloud_params is None:
            raise ValueError("Invalid value for `cloud_params`, must not be `None`")  # noqa: E501

        self._cloud_params = cloud_params

    @property
    def leaf(self) -> List[Device]:
        """Gets the leaf of this NewDeployment


        :return: The leaf of this NewDeployment.
        :rtype: List[Device]
        """
        return self._leaf

    @leaf.setter
    def leaf(self, leaf: List[Device]):
        """Sets the leaf of this NewDeployment.


        :param leaf: The leaf of this NewDeployment.
        :type leaf: List[Device]
        """

        self._leaf = leaf

    @property
    def gateway(self) -> List[Device]:
        """Gets the gateway of this NewDeployment


        :return: The gateway of this NewDeployment.
        :rtype: List[str]
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway: List[Device]):
        """Sets the gateway of this NewDeployment.


        :param gateway: The leaf of this NewDeployment.
        :type gateway: List[Device]
        """

        self._gateway = gateway