# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from project_api import util
from project_api.models.base_model_ import Model


class OutputType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """OutputType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OutputType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OutputType of this OutputType.  # noqa: E501
        :rtype: OutputType
        """
        return util.deserialize_model(dikt, cls)

    @staticmethod
    def from_str(label):
        return label