# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from project_api.models.base_model_ import Model
from project_api.models.patch_inference_model_reference_new_model_name_reference import PatchInferenceModelReferenceNewModelNameReference  # noqa: F401,E501
from project_api import util


class PatchInferenceModelReference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, new_model_name_reference: PatchInferenceModelReferenceNewModelNameReference=None):  # noqa: E501
        """PatchInferenceModelReference - a model defined in Swagger

        :param new_model_name_reference: The new_model_name_reference of this PatchInferenceModelReference.  # noqa: E501
        :type new_model_name_reference: PatchInferenceModelReferenceNewModelNameReference
        """
        self.swagger_types = {
            'new_model_name_reference': PatchInferenceModelReferenceNewModelNameReference
        }

        self.attribute_map = {
            'new_model_name_reference': 'new_model_name_reference'
        }
        self._new_model_name_reference = new_model_name_reference

    @classmethod
    def from_dict(cls, dikt) -> 'PatchInferenceModelReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PatchInferenceModelReference of this PatchInferenceModelReference.  # noqa: E501
        :rtype: PatchInferenceModelReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def new_model_name_reference(self) -> PatchInferenceModelReferenceNewModelNameReference:
        """Gets the new_model_name_reference of this PatchInferenceModelReference.


        :return: The new_model_name_reference of this PatchInferenceModelReference.
        :rtype: PatchInferenceModelReferenceNewModelNameReference
        """
        return self._new_model_name_reference

    @new_model_name_reference.setter
    def new_model_name_reference(self, new_model_name_reference: PatchInferenceModelReferenceNewModelNameReference):
        """Sets the new_model_name_reference of this PatchInferenceModelReference.


        :param new_model_name_reference: The new_model_name_reference of this PatchInferenceModelReference.
        :type new_model_name_reference: PatchInferenceModelReferenceNewModelNameReference
        """

        self._new_model_name_reference = new_model_name_reference
