# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from project_api import util
from project_api.models.base_model_ import Model


class TrainingType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OFFLINE = "offline"
    ONLINE = "online"
    def __init__(self):  # noqa: E501
        """TrainingType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TrainingType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainingType of this TrainingType.  # noqa: E501
        :rtype: TrainingType
        """
        return util.deserialize_model(dikt, cls)
