# coding: utf-8

from __future__ import absolute_import
from datetime import datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from project_api import util
from project_api.models.base_model_ import Model

class NewTraining(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, configuration: str=None, reports: List=None, artifacts: List=None, creation_time: datetime = None, last_update_time: datetime = None):  # noqa: E501
        """NewTraining - a training defined in Swagger

        :param tool: The name of the tool in this Training.  # noqa: E501
        :type tool: str
        :param tool_version: The version of this tool.  # noqa: E501
        :type tool_version: str
        """
        self.swagger_types = {
            'type': str,
            'configuration': str,
            'reports': List[str],
            'artifacts': List[str],
            'creation_time': str,
            'last_update_time': str
        }

        self.attribute_map = {
            'type': 'type',
            'configuration': 'configuration',
            'reports': 'reports',
            'artifacts': 'artifacts',
            'creation_time': 'creation_time',
            'last_update_time': 'last_update_time',
        }
        self._type = type
        self._configuration = configuration
        self._reports = reports
        self._artifacts = artifacts
        self._creation_time = str(creation_time)
        self._last_update_time = str(last_update_time)
        

    @classmethod
    def from_dict(cls, dikt) -> 'NewTraining':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewTraining of this NewTraining.  # noqa: E501
        :rtype: NewTraining
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this NewTraining.


        :return: The type of this NewTraining.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the tool of this NewTraining.


        :param tool: The tool of this NewTraining.
        :type tool: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def configuration(self) -> str:
        """Gets the name of this Pipeline.


        :return: The name of this Pipeline.
        :rtype: str
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration: str):
        """Sets the name of this Pipeline.


        :param name: The name of this Pipeline.
        :type name: str
        """
        if configuration is None:
            raise ValueError("Invalid value for `configuration`, must not be `None`")  # noqa: E501

        self._configuration = configuration

    @property
    def reports(self) -> List[str]:
        """Gets the description of this Pipeline.


        :return: The description of this Pipeline.
        :rtype: str
        """
        return self._reports

    @reports.setter
    def reports(self, reports: List[str]):
        """Sets the description of this Pipeline.


        :param description: The description of this Pipeline.
        :type description: str
        """
        if reports is None:
            raise ValueError("Invalid value for `reports`, must not be `None`")  # noqa: E501

        self._reports = reports

    @property
    def artifacts(self) -> List[str]:
        """Gets the description of this Pipeline.


        :return: The description of this Pipeline.
        :rtype: str
        """
        return self._artifacts

    @artifacts.setter
    def artifacts(self, artifacts: List[str]):
        """Sets the description of this Pipeline.


        :param description: The description of this Pipeline.
        :type description: str
        """
        if artifacts is None:
            raise ValueError("Invalid value for `artifacts`, must not be `None`")  # noqa: E501

        self._artifacts = artifacts
        
    @property
    def creation_time(self) -> str:
        return self._creation_time
       
    @property
    def last_update_time(self) -> str:
        return self._last_update_time

    @last_update_time.setter
    def last_update_time(self, value: datetime):
        self._last_update_time = str(value)
 