# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.model_model_metadata import ModelModelMetadata

class TestModelModelMetadata(unittest.TestCase):
    """ModelModelMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelModelMetadata:
        """Test ModelModelMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelModelMetadata`
        """
        model = ModelModelMetadata()
        if include_optional:
            return ModelModelMetadata(
                type = 'classifier',
                classes = [
                    '01'
                    ]
            )
        else:
            return ModelModelMetadata(
        )
        """

    def testModelModelMetadata(self):
        """Test ModelModelMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
