# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectApi()

    def tearDown(self) -> None:
        pass

    def test_app_delete_project(self) -> None:
        """Test case for app_delete_project

        Delete project associated to the given name.
        """
        pass

    def test_app_get_project(self) -> None:
        """Test case for app_get_project

        Get project associated to the given name.
        """
        pass

    def test_app_get_project_icon(self) -> None:
        """Test case for app_get_project_icon

        Get project icon associated to the given name.
        """
        pass

    def test_app_get_template_project_icon(self) -> None:
        """Test case for app_get_template_project_icon

        Get project icon associated to the given name.
        """
        pass


if __name__ == '__main__':
    unittest.main()
