# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.model_type import ModelType

class TestModelType(unittest.TestCase):
    """ModelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelType(self):
        """Test ModelType"""
        # inst = ModelType()

if __name__ == '__main__':
    unittest.main()
