# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.public_projects_activity_api import PublicProjectsActivityApi


class TestPublicProjectsActivityApi(unittest.TestCase):
    """PublicProjectsActivityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicProjectsActivityApi()

    def tearDown(self) -> None:
        pass

    def test_app_get_public_projects_activity(self) -> None:
        """Test case for app_get_public_projects_activity

        Get the file contents of artifacts, reports or configuration of the activity for public projects
        """
        pass


if __name__ == '__main__':
    unittest.main()
