# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.app_create_deployment_id_request_applications_inner import AppCreateDeploymentIdRequestApplicationsInner

class TestAppCreateDeploymentIdRequestApplicationsInner(unittest.TestCase):
    """AppCreateDeploymentIdRequestApplicationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppCreateDeploymentIdRequestApplicationsInner:
        """Test AppCreateDeploymentIdRequestApplicationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppCreateDeploymentIdRequestApplicationsInner`
        """
        model = AppCreateDeploymentIdRequestApplicationsInner()
        if include_optional:
            return AppCreateDeploymentIdRequestApplicationsInner(
                device_manifest_uri = '',
                device_template_id = '',
                device_template_uri = '',
                image_uri = '',
                module_id = '',
                type = '',
                protocol = 56,
                binary_id = 56,
                binary_uri = ''
            )
        else:
            return AppCreateDeploymentIdRequestApplicationsInner(
        )
        """

    def testAppCreateDeploymentIdRequestApplicationsInner(self):
        """Test AppCreateDeploymentIdRequestApplicationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
