# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.artifacts_api import ArtifactsApi


class TestArtifactsApi(unittest.TestCase):
    """ArtifactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArtifactsApi()

    def tearDown(self) -> None:
        pass

    def test_app_download_activity_artifacts(self) -> None:
        """Test case for app_download_activity_artifacts

        Download Activity Job Artifacts
        """
        pass


if __name__ == '__main__':
    unittest.main()
