# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.new_project import NewProject

class TestNewProject(unittest.TestCase):
    """NewProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewProject:
        """Test NewProject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewProject`
        """
        model = NewProject()
        if include_optional:
            return NewProject(
                project_name_to_clone = 'z0',
                ai_project_name = 'z0',
                description = '',
                reference = '',
                version = '',
                creation_time = '',
                last_update_time = ''
            )
        else:
            return NewProject(
        )
        """

    def testNewProject(self):
        """Test NewProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
