# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.runtime import Runtime

class TestRuntime(unittest.TestCase):
    """Runtime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Runtime:
        """Test Runtime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Runtime`
        """
        model = Runtime()
        if include_optional:
            return Runtime(
                type = '',
                jobs = [
                    {"name":"job-alias","version":"job-version","template_id":"job-template-id"}
                    ]
            )
        else:
            return Runtime(
        )
        """

    def testRuntime(self):
        """Test Runtime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
