# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.deployment_api import DeploymentApi


class TestDeploymentApi(unittest.TestCase):
    """DeploymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentApi()

    def tearDown(self) -> None:
        pass

    def test_app_create_deployment_id(self) -> None:
        """Test case for app_create_deployment_id

        Create deployment of a project
        """
        pass

    def test_app_delete_deployment_id(self) -> None:
        """Test case for app_delete_deployment_id

        Delete the deployment ID of a project
        """
        pass

    def test_app_get_deployment_gateway(self) -> None:
        """Test case for app_get_deployment_gateway

        Get files relating to a gateway device
        """
        pass

    def test_app_get_deployment_leaf(self) -> None:
        """Test case for app_get_deployment_leaf

        Get files relating to a leaf device
        """
        pass

    def test_app_update_deployment_id(self) -> None:
        """Test case for app_update_deployment_id

        Update deployment of a project
        """
        pass


if __name__ == '__main__':
    unittest.main()
