# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.app_update_deployment_id_request_gateway_inner import AppUpdateDeploymentIdRequestGatewayInner

class TestAppUpdateDeploymentIdRequestGatewayInner(unittest.TestCase):
    """AppUpdateDeploymentIdRequestGatewayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppUpdateDeploymentIdRequestGatewayInner:
        """Test AppUpdateDeploymentIdRequestGatewayInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppUpdateDeploymentIdRequestGatewayInner`
        """
        model = AppUpdateDeploymentIdRequestGatewayInner()
        if include_optional:
            return AppUpdateDeploymentIdRequestGatewayInner(
                device_id = '',
                device_id = '',
                application = '',
                description = '',
                display_name = '',
                wifi_mode = ''
            )
        else:
            return AppUpdateDeploymentIdRequestGatewayInner(
        )
        """

    def testAppUpdateDeploymentIdRequestGatewayInner(self):
        """Test AppUpdateDeploymentIdRequestGatewayInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
