# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.app_update_deployment_id_request_leaf_inner import AppUpdateDeploymentIdRequestLeafInner

class TestAppUpdateDeploymentIdRequestLeafInner(unittest.TestCase):
    """AppUpdateDeploymentIdRequestLeafInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppUpdateDeploymentIdRequestLeafInner:
        """Test AppUpdateDeploymentIdRequestLeafInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppUpdateDeploymentIdRequestLeafInner`
        """
        model = AppUpdateDeploymentIdRequestLeafInner()
        if include_optional:
            return AppUpdateDeploymentIdRequestLeafInner(
                device_id = '',
                device_id = '',
                gateway_id = '',
                description = '',
                display_name = '',
                datalogging = project_api_client.models.app_create_deployment_id_request_deployment_leaf_inner_datalogging.app_create_deployment_id_request_deployment_leaf_inner_datalogging(
                    application = '', 
                    firmware_update = True, ),
                inference = project_api_client.models.app_create_deployment_id_request_deployment_leaf_inner_inference.app_create_deployment_id_request_deployment_leaf_inner_inference(
                    application = '', 
                    firmware_update = True, 
                    models = [
                        project_api_client.models.app_create_deployment_id_request_deployment_leaf_inner_inference_models_inner.app_create_deployment_id_request_deployment_leaf_inner_inference_models_inner(
                            artifact_type = '', 
                            component_name = '', 
                            model_name_reference = '', )
                        ], )
            )
        else:
            return AppUpdateDeploymentIdRequestLeafInner(
        )
        """

    def testAppUpdateDeploymentIdRequestLeafInner(self):
        """Test AppUpdateDeploymentIdRequestLeafInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
