# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.model_api import ModelApi


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModelApi()

    def tearDown(self) -> None:
        pass

    def test_app_delete_model(self) -> None:
        """Test case for app_delete_model

        Delete model associated to the given name.
        """
        pass


if __name__ == '__main__':
    unittest.main()
