# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.job_artifact import JobArtifact

class TestJobArtifact(unittest.TestCase):
    """JobArtifact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobArtifact:
        """Test JobArtifact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobArtifact`
        """
        model = JobArtifact()
        if include_optional:
            return JobArtifact(
                s3_url = '',
                job = {"name":"job-alias","version":"job-version","template_id":"job-template-id"},
                artifacts = [
                    ''
                    ],
                reports = [
                    ''
                    ]
            )
        else:
            return JobArtifact(
        )
        """

    def testJobArtifact(self):
        """Test JobArtifact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
