# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_app_create_project(self) -> None:
        """Test case for app_create_project

        Create new project
        """
        pass

    def test_app_get_projects(self) -> None:
        """Test case for app_get_projects

        Projects list
        """
        self.api.app_get_projects()  # noqa: E501
        # Add assertions to verify the response if needed
        pass


if __name__ == '__main__':
    unittest.main()
