# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.job_api import JobApi


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobApi()

    def tearDown(self) -> None:
        pass

    def test_app_create_job_for_activity(self) -> None:
        """Test case for app_create_job_for_activity

        Create new Activity Job and add a job json object to the model activity in Project JSON file
        """
        pass


if __name__ == '__main__':
    unittest.main()
