# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.models.deployment_cloud_params import DeploymentCloudParams

class TestDeploymentCloudParams(unittest.TestCase):
    """DeploymentCloudParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentCloudParams:
        """Test DeploymentCloudParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentCloudParams`
        """
        model = DeploymentCloudParams()
        if include_optional:
            return DeploymentCloudParams(
                type = '0',
                app_url = ''
            )
        else:
            return DeploymentCloudParams(
                type = '0',
                app_url = '',
        )
        """

    def testDeploymentCloudParams(self):
        """Test DeploymentCloudParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
