# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.project_templates_api import ProjectTemplatesApi


class TestProjectTemplatesApi(unittest.TestCase):
    """ProjectTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_app_get_templates_projects(self) -> None:
        """Test case for app_get_templates_projects

        Project templates list
        """
        pass


if __name__ == '__main__':
    unittest.main()
