# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.activity_api import ActivityApi


class TestActivityApi(unittest.TestCase):
    """ActivityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivityApi()

    def tearDown(self) -> None:
        pass

    def test_app_create_activity(self) -> None:
        """Test case for app_create_activity

        Create new Activity
        """
        pass

    def test_app_delete_activity(self) -> None:
        """Test case for app_delete_activity

        Delete the activity associated to the given name.
        """
        pass

    def test_app_get_activity(self) -> None:
        """Test case for app_get_activity

        Get the file contents of artifacts, reports or configuration of the activity
        """
        pass

    def test_app_patch_activity(self) -> None:
        """Test case for app_patch_activity

        Update partial Activity JSON
        """
        pass

    def test_app_update_activity(self) -> None:
        """Test case for app_update_activity

        Update Activity JSON
        """
        pass


if __name__ == '__main__':
    unittest.main()
