# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from project_api_client.api.applications_api import ApplicationsApi


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationsApi()

    def tearDown(self) -> None:
        pass

    def test_app_delete_application_id(self) -> None:
        """Test case for app_delete_application_id

        Delete the application ID of a project
        """
        pass

    def test_app_update_application_id(self) -> None:
        """Test case for app_update_application_id

        Patch the application ID of a project
        """
        pass


if __name__ == '__main__':
    unittest.main()
