# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from project_api.models.base_model_ import Model
from project_api.models.device_models import DeviceModels  # noqa: F401,E501
from project_api import util


class DeviceApplication(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, application: str=None, firmware_update: bool=None, models: List[DeviceModels]=None):  # noqa: E501
        """DeviceApplication - a model defined in Swagger

        :param application: The application UUID of this DeviceApplication.  # noqa: E501
        :type application: str
        :param firmware_update: The firmware_update option of this DeviceApplication.  # noqa: E501
        :type firmware_update: bool
        :param models: The models of this DeviceApplication.  # noqa: E501
        :type models: List[DeviceModels]
        """
        self.swagger_types = {
            'application': str,
            'firmware_update': bool,
            'models': List[DeviceModels]
        }

        self.attribute_map = {
            'application': 'application',
            'firmware_update': 'firmware_update',
            'models': 'models'
        }
        self._application = application
        self._firmware_update = firmware_update
        self._models = models

    @classmethod
    def from_dict(cls, dikt) -> 'DeviceApplication':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceApplication of this DeviceApplication.  # noqa: E501
        :rtype: DeviceApplication
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application(self) -> str:
        """Gets the application of this DeviceApplication.


        :return: The application of this DeviceApplication.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application: str):
        """Sets the application of this DeviceApplication.


        :param application: The application of this DeviceApplication.
        :type application: str
        """

        self._application = application

    @property
    def firmware_update(self) -> bool:
        """Gets the firmware_update of this DeviceApplication.


        :return: The firmware_update of this DeviceApplication.
        :rtype: str
        """
        return self._firmware_update

    @firmware_update.setter
    def firmware_update(self, firmware_update: bool):
        """Sets the firmware_update of this DeviceApplication.


        :param firmware_update: The firmware_update of this DeviceApplication.
        :type firmware_update: bool
        """

        self._firmware_update = firmware_update

    @property
    def models(self) -> List[DeviceModels]:
        """Gets the models of this DeviceApplication.


        :return: The models of this DeviceApplication.
        :rtype: float
        """
        return self._models

    @models.setter
    def models(self, models: List[DeviceModels]):
        """Sets the models of this DeviceApplication.


        :param models: The models of this DeviceApplication.
        :type models: List[DeviceModels]
        """

        self._models = models
