# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from project_api import util
from project_api.models.base_model_ import Model


class InputType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BINARY_HSD = "binary_hsd"
    CSV_UNICO = "csv_unico"
    IMAGE = "image"
    def __init__(self):  # noqa: E501
        """InputType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'InputType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InputType of this InputType.  # noqa: E501
        :rtype: InputType
        """
        return util.deserialize_model(dikt, cls)

    @staticmethod
    def from_str(label):
        if label == InputType.BINARY_HSD:
            return InputType.BINARY_HSD
        elif label == InputType.STRED_BIN:
            return InputType.STRED_BIN
        elif label == InputType.OPENMV_STM32_BIN:
            return InputType.OPENMV_STM32_BIN
        else:
            raise NotImplementedError