# coding: utf-8

# flake8: noqa

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ActivityApi",
    "ApplicationsApi",
    "ArtifactsApi",
    "ConfigurationApi",
    "DeploymentApi",
    "DeploymentArtifactsApi",
    "JobApi",
    "ModelApi",
    "ModelsApi",
    "ProjectApi",
    "ProjectTemplatesApi",
    "ProjectsApi",
    "PublicProjectsActivityApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AppCreateDeploymentIdRequest",
    "AppCreateDeploymentIdRequestApplicationsInner",
    "AppCreateDeploymentIdRequestDeployment",
    "AppCreateDeploymentIdRequestDeploymentCloudParams",
    "AppCreateDeploymentIdRequestDeploymentGatewayInner",
    "AppCreateDeploymentIdRequestDeploymentLeafInner",
    "AppCreateDeploymentIdRequestDeploymentLeafInnerDatalogging",
    "AppCreateDeploymentIdRequestDeploymentLeafInnerInference",
    "AppCreateDeploymentIdRequestDeploymentLeafInnerInferenceModelsInner",
    "AppPatchActivityRequest",
    "AppUpdateDeploymentIdRequest",
    "AppUpdateDeploymentIdRequestGatewayInner",
    "AppUpdateDeploymentIdRequestLeafInner",
    "Dataset",
    "Deployment",
    "DeploymentCloudParams",
    "DeploymentConfiguration",
    "Device",
    "DeviceApplication",
    "DeviceModelsInner",
    "EFSUsage",
    "Job",
    "JobArtifact",
    "Model",
    "ModelModelMetadata",
    "ModelType",
    "NewModel",
    "NewProject",
    "NewTraining",
    "Project",
    "Runtime",
    "Target",
    "Tool",
    "Training",
    "TrainingMLCConfiguration",
    "TrainingType",
    "UpdateDeployment",
    "UpdateDeploymentCloudCredentials",
    "UpdateDevice",
    "UpdateDeviceCloudCredentials",
]

# import apis into sdk package
from project_api_client.api.activity_api import ActivityApi as ActivityApi
from project_api_client.api.applications_api import ApplicationsApi as ApplicationsApi
from project_api_client.api.artifacts_api import ArtifactsApi as ArtifactsApi
from project_api_client.api.configuration_api import ConfigurationApi as ConfigurationApi
from project_api_client.api.deployment_api import DeploymentApi as DeploymentApi
from project_api_client.api.deployment_artifacts_api import DeploymentArtifactsApi as DeploymentArtifactsApi
from project_api_client.api.job_api import JobApi as JobApi
from project_api_client.api.model_api import ModelApi as ModelApi
from project_api_client.api.models_api import ModelsApi as ModelsApi
from project_api_client.api.project_api import ProjectApi as ProjectApi
from project_api_client.api.project_templates_api import ProjectTemplatesApi as ProjectTemplatesApi
from project_api_client.api.projects_api import ProjectsApi as ProjectsApi
from project_api_client.api.public_projects_activity_api import PublicProjectsActivityApi as PublicProjectsActivityApi

# import ApiClient
from project_api_client.api_response import ApiResponse as ApiResponse
from project_api_client.api_client import ApiClient as ApiClient
from project_api_client.configuration import Configuration as Configuration
from project_api_client.exceptions import OpenApiException as OpenApiException
from project_api_client.exceptions import ApiTypeError as ApiTypeError
from project_api_client.exceptions import ApiValueError as ApiValueError
from project_api_client.exceptions import ApiKeyError as ApiKeyError
from project_api_client.exceptions import ApiAttributeError as ApiAttributeError
from project_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from project_api_client.models.app_create_deployment_id_request import AppCreateDeploymentIdRequest as AppCreateDeploymentIdRequest
from project_api_client.models.app_create_deployment_id_request_applications_inner import AppCreateDeploymentIdRequestApplicationsInner as AppCreateDeploymentIdRequestApplicationsInner
from project_api_client.models.app_create_deployment_id_request_deployment import AppCreateDeploymentIdRequestDeployment as AppCreateDeploymentIdRequestDeployment
from project_api_client.models.app_create_deployment_id_request_deployment_cloud_params import AppCreateDeploymentIdRequestDeploymentCloudParams as AppCreateDeploymentIdRequestDeploymentCloudParams
from project_api_client.models.app_create_deployment_id_request_deployment_gateway_inner import AppCreateDeploymentIdRequestDeploymentGatewayInner as AppCreateDeploymentIdRequestDeploymentGatewayInner
from project_api_client.models.app_create_deployment_id_request_deployment_leaf_inner import AppCreateDeploymentIdRequestDeploymentLeafInner as AppCreateDeploymentIdRequestDeploymentLeafInner
from project_api_client.models.app_create_deployment_id_request_deployment_leaf_inner_datalogging import AppCreateDeploymentIdRequestDeploymentLeafInnerDatalogging as AppCreateDeploymentIdRequestDeploymentLeafInnerDatalogging
from project_api_client.models.app_create_deployment_id_request_deployment_leaf_inner_inference import AppCreateDeploymentIdRequestDeploymentLeafInnerInference as AppCreateDeploymentIdRequestDeploymentLeafInnerInference
from project_api_client.models.app_create_deployment_id_request_deployment_leaf_inner_inference_models_inner import AppCreateDeploymentIdRequestDeploymentLeafInnerInferenceModelsInner as AppCreateDeploymentIdRequestDeploymentLeafInnerInferenceModelsInner
from project_api_client.models.app_patch_activity_request import AppPatchActivityRequest as AppPatchActivityRequest
from project_api_client.models.app_update_deployment_id_request import AppUpdateDeploymentIdRequest as AppUpdateDeploymentIdRequest
from project_api_client.models.app_update_deployment_id_request_gateway_inner import AppUpdateDeploymentIdRequestGatewayInner as AppUpdateDeploymentIdRequestGatewayInner
from project_api_client.models.app_update_deployment_id_request_leaf_inner import AppUpdateDeploymentIdRequestLeafInner as AppUpdateDeploymentIdRequestLeafInner
from project_api_client.models.dataset import Dataset as Dataset
from project_api_client.models.deployment import Deployment as Deployment
from project_api_client.models.deployment_cloud_params import DeploymentCloudParams as DeploymentCloudParams
from project_api_client.models.deployment_configuration import DeploymentConfiguration as DeploymentConfiguration
from project_api_client.models.device import Device as Device
from project_api_client.models.device_application import DeviceApplication as DeviceApplication
from project_api_client.models.device_models_inner import DeviceModelsInner as DeviceModelsInner
from project_api_client.models.efs_usage import EFSUsage as EFSUsage
from project_api_client.models.job import Job as Job
from project_api_client.models.job_artifact import JobArtifact as JobArtifact
from project_api_client.models.model import Model as Model
from project_api_client.models.model_model_metadata import ModelModelMetadata as ModelModelMetadata
from project_api_client.models.model_type import ModelType as ModelType
from project_api_client.models.new_model import NewModel as NewModel
from project_api_client.models.new_project import NewProject as NewProject
from project_api_client.models.new_training import NewTraining as NewTraining
from project_api_client.models.project import Project as Project
from project_api_client.models.runtime import Runtime as Runtime
from project_api_client.models.target import Target as Target
from project_api_client.models.tool import Tool as Tool
from project_api_client.models.training import Training as Training
from project_api_client.models.training_mlc_configuration import TrainingMLCConfiguration as TrainingMLCConfiguration
from project_api_client.models.training_type import TrainingType as TrainingType
from project_api_client.models.update_deployment import UpdateDeployment as UpdateDeployment
from project_api_client.models.update_deployment_cloud_credentials import UpdateDeploymentCloudCredentials as UpdateDeploymentCloudCredentials
from project_api_client.models.update_device import UpdateDevice as UpdateDevice
from project_api_client.models.update_device_cloud_credentials import UpdateDeviceCloudCredentials as UpdateDeviceCloudCredentials
