# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from project_api_client.models.deployment_cloud_params import DeploymentCloudParams
from project_api_client.models.deployment_configuration import DeploymentConfiguration
from typing import Optional, Set
from typing_extensions import Self

class Deployment(BaseModel):
    """
    Deployment
    """ # noqa: E501
    uuid: Annotated[str, Field(strict=True)]
    display_name: Annotated[str, Field(min_length=1, strict=True)]
    description: Optional[StrictStr] = None
    last_deploy_time: Optional[datetime] = None
    last_deploy_result: Optional[StrictStr] = None
    cloud_params: DeploymentCloudParams
    configuration: Optional[DeploymentConfiguration] = None
    __properties: ClassVar[List[str]] = ["uuid", "display_name", "description", "last_deploy_time", "last_deploy_result", "cloud_params", "configuration"]

    @field_validator('uuid')
    def uuid_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_-]+$/")
        return value

    @field_validator('last_deploy_result')
    def last_deploy_result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['deploy_success', 'deploy_error', 'undeploy_success', 'undeploy_error']):
            raise ValueError("must be one of enum values ('deploy_success', 'deploy_error', 'undeploy_success', 'undeploy_error')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Deployment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cloud_params
        if self.cloud_params:
            _dict['cloud_params'] = self.cloud_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of configuration
        if self.configuration:
            _dict['configuration'] = self.configuration.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Deployment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "display_name": obj.get("display_name"),
            "description": obj.get("description"),
            "last_deploy_time": obj.get("last_deploy_time"),
            "last_deploy_result": obj.get("last_deploy_result"),
            "cloud_params": DeploymentCloudParams.from_dict(obj["cloud_params"]) if obj.get("cloud_params") is not None else None,
            "configuration": DeploymentConfiguration.from_dict(obj["configuration"]) if obj.get("configuration") is not None else None
        })
        return _obj


