# coding: utf-8

"""
    STAIoTCraft - Project API

    REST API to access STAIoTCraft Back-End web-service User Projects

    The version of the OpenAPI document: 3.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from project_api_client.models.device_models_inner import DeviceModelsInner
from typing import Optional, Set
from typing_extensions import Self

class Device(BaseModel):
    """
    Device
    """ # noqa: E501
    device_id: StrictStr
    description: StrictStr
    gateway_id: Optional[StrictStr] = None
    selected_model_name: Optional[StrictStr] = None
    module_id: Optional[StrictStr] = None
    configuration_uri: Optional[StrictStr] = None
    device_manifest_uri: Optional[StrictStr] = None
    device_template_uri: Optional[StrictStr] = None
    device_template_id: Optional[StrictStr] = None
    wifi_mode: Optional[StrictStr] = None
    models: Optional[List[DeviceModelsInner]] = None
    __properties: ClassVar[List[str]] = ["device_id", "description", "gateway_id", "selected_model_name", "module_id", "configuration_uri", "device_manifest_uri", "device_template_uri", "device_template_id", "wifi_mode", "models"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Device from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item_models in self.models:
                if _item_models:
                    _items.append(_item_models.to_dict())
            _dict['models'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Device from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "device_id": obj.get("device_id"),
            "description": obj.get("description"),
            "gateway_id": obj.get("gateway_id"),
            "selected_model_name": obj.get("selected_model_name"),
            "module_id": obj.get("module_id"),
            "configuration_uri": obj.get("configuration_uri"),
            "device_manifest_uri": obj.get("device_manifest_uri"),
            "device_template_uri": obj.get("device_template_uri"),
            "device_template_id": obj.get("device_template_id"),
            "wifi_mode": obj.get("wifi_mode"),
            "models": [DeviceModelsInner.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None
        })
        return _obj


